### ISSUE TITLE
Error occurred while installing component

### ISSUE THREAD

**Issue by jwangb7111** [baumwollschaf/RDOpenAI#1]
Hi,

The IDE compiler raised error message while installing component as shown below:
![image](https://user-images.githubusercontent.com/34438897/218240848-048cb77b-d2d5-47da-9473-12683d877ee7.png)

Am I doing something wrong?
Thx
JW

**Comment by baumwollschaf** [comment]
Hi, I'll check this evening. ok. Cheers, Ralph

Am Sa., 11. Feb. 2023 um 05:54 Uhr schrieb jwangb7111 <
***@***.***>:

**Comment by baumwollschaf** [comment]
fixed. pls try again.

Am Sa., 11. Feb. 2023 um 10:39 Uhr schrieb Ralph Dietrich <
***@***.***>:

**Comment by baumwollschaf** [comment]
The component has been developed in Delphi 11.2.
property ContentTypeStr is not available in versions below 11.1.

**Comment by baumwollschaf** [comment]
I'll add a define next time.
