### ISSUE TITLE
gpt 3.5

### ISSUE THREAD

**Issue by Marijsoft** [baumwollschaf/RDOpenAI#2]
when you set the model gpt-3.5-turbo have error the url endpoint is different https://api.openai.com/v1/chat/completions and custom body

**Comment by baumwollschaf** [comment]
Thank you!

(mobil)

Marijsoft ***@***.***> schrieb am Di., 28. März 2023, 14:59:

**Comment by baumwollschaf** [comment]
I'll fix it this evening...

(mobil)

Ralph Dietrich ***@***.***> schrieb am Di., 28. März 2023,
15:17:

**Comment by baumwollschaf** [comment]
fixed

**Comment by baumwollschaf** [comment]
I'll re-fix it in a few days... i'm sick...

(mobil)

Ralph Dietrich ***@***.***> schrieb am Di., 28. März 2023,
15:23:

**Comment by Marijsoft** [comment]
ok take care your health, i tried again to download your code again but it doesn't go same problem 
![1](https://user-images.githubusercontent.com/4884515/228323581-a6a564f8-4e37-4965-98a2-002f8ddd106c.png)
![2](https://user-images.githubusercontent.com/4884515/228323585-6f67a02d-5dc4-49ff-8574-80dfd946d179.png)
![3](https://user-images.githubusercontent.com/4884515/228323587-1042c46d-226e-4c47-bdba-3010bb63e54f.png)

**Comment by baumwollschaf** [comment]
ok, try now please.

**Comment by baumwollschaf** [comment]
Chat Completions is a complete different model and ViewModel

**Comment by baumwollschaf** [comment]
Thanks for your advice

**Comment by Marijsoft** [comment]
yes!!!! :) now it's good :) thank u mate!

**Comment by Marijsoft** [comment]
i hope u are fine , about the health

**Comment by baumwollschaf** [comment]
Caught a cold. Thanks

Marijsoft ***@***.***> schrieb am Di., 28. März 2023, 21:07:
