### ISSUE TITLE
Error: Too Many Requests

### ISSUE THREAD

**Issue by levelg0** [baumwollschaf/RDOpenAI#4]
I'm trying to test sample project with my API key and I get below errors and Models drop down shows no models. Using Delphi 11.3
Error: 
Error: Too Many Requests

My account doesn't show any API requests from same API key.

**Comment by baumwollschaf** [comment]
Hi,

You need your own API Key from here:
https://platform.openai.com/account/api-keys

Obviously it is still my one.

Cheers

(mobil)

levelg0 ***@***.***> schrieb am Do., 16. Nov. 2023, 19:19:

**Comment by baumwollschaf** [comment]
You must set an ApiKey (before created, Link last message) in
the TRDChatGpt component. At design time or runtime.

(mobil)

Ralph Dietrich ***@***.***> schrieb am Fr., 17. Nov. 2023,
06:33:

**Comment by baumwollschaf** [comment]
You must set an ApiKey (before created, Link last message) in
the TRDChatGpt component. At design time or runtime.


levelg0 ***@***.***> schrieb am Do., 16. Nov. 2023, 19:19:

**Comment by baumwollschaf** [comment]
ApiKey

**Comment by levelg0** [comment]
I already indicated in my original message that I am using my own API Key. 
![Screenshot 2023-11-16 222052](https://github.com/baumwollschaf/RDOpenAI/assets/88561454/6eadba91-f49c-4a38-b2c6-2f2af1a484d7)

**Comment by baumwollschaf** [comment]
Then you likely have to pay. Same for me. Otherwise register new ApiKeys
with different cell Phone (i.e. new number) and new account.

(mobil)

levelg0 ***@***.***> schrieb am Fr., 17. Nov. 2023, 07:22:

**Comment by baumwollschaf** [comment]
"Too Many Requests" means your free contingent is over.

**Comment by levelg0** [comment]
Thanks for the tip. I already had paid account but I had to add payment method to API section again and create a new API key to get it to work. Chat works now, however, Models drop down list is still empty.

**Comment by baumwollschaf** [comment]
It's been a while since I did this. Why don't you try another model or
something?!

Am Fr., 17. Nov. 2023 um 07:48 Uhr schrieb levelg0 ***@***.***

**Comment by baumwollschaf** [comment]
A lot has happened there and maybe my default model is no longer
correct...?!

Am Fr., 17. Nov. 2023 um 07:48 Uhr schrieb levelg0 ***@***.***

**Comment by baumwollschaf** [comment]
set the ApiKey at runtime before loading models...

Am Fr., 17. Nov. 2023 um 07:48 Uhr schrieb levelg0 ***@***.***

**Comment by levelg0** [comment]
Loading API key at runtime didn't help. It's okay I'll try to look into source code for more clues.

**Comment by baumwollschaf** [comment]
Check the API doc if any endpoint has changed or sth...

(mobil)

levelg0 ***@***.***> schrieb am Fr., 17. Nov. 2023, 17:43:

**Comment by baumwollschaf** [comment]
apparently there are no more models...
No "/v1/models" or sth
Then simply ignore and hardcode those in a list or sth.

(mobil)

Ralph Dietrich ***@***.***> schrieb am Fr., 17. Nov. 2023,
17:49:

**Comment by baumwollschaf** [comment]
(mobil)

levelg0 ***@***.***> schrieb am Fr., 17. Nov. 2023, 17:43:

**Comment by baumwollschaf** [comment]
I'll simply remove the part with LoadModels.

**Comment by levelg0** [comment]
Thanks I'll get it fixed on my copy

**Comment by levelg0** [comment]
could we discuss a related project in private?

**Comment by baumwollschaf** [comment]
Check
https://platform.openai.com/docs/api-reference/models/list
Obviously still available.
I'll check next week.

**Comment by baumwollschaf** [comment]
> Check https://platform.openai.com/docs/api-reference/models/list Obviously still available. I'll check next week.

GET
 
https://api.openai.com/v1/models

**Comment by levelg0** [comment]
The reason drop down list is not populated is because AModels.Data[i].Root is empty in RDChatGpt1ModelsLoaded.
Using AModels.Data[i].Id works fine.

procedure TForm1.RDChatGpt1ModelsLoaded(Sender: TObject; AModels: TModels);
begin
  Assert(AModels <> nil);
  ComboBox1.Items.Clear;
  for var i: Integer := 0 to AModels.Data.Count - 1 do
  begin
    ComboBox1.Items.Add(AModels.Data[i].Root);  <----------------- THIS IS EMPTY
  end;
  ComboBox1.ItemIndex := ComboBox1.Items.IndexOf(RDChatGpt1.Model);
  ComboBox1.Enabled := ComboBox1.ItemIndex <> -1;
end;

**Comment by baumwollschaf** [comment]
Ok thank you

(mobil)

levelg0 ***@***.***> schrieb am Mo., 20. Nov. 2023, 19:06:
