### ISSUE TITLE
RDopenai does not work in Delphi Vs 12

### ISSUE THREAD

**Issue by Heinzneumann** [baumwollschaf/RDOpenAI#5]
The added Example does not work in delphi 12. Is there an Update available?

**Comment by baumwollschaf** [comment]
I'll fix it this Weekend.

(mobil)

Heinzneumann ***@***.***> schrieb am Sa., 27. Jan. 2024,
09:46:

**Comment by Heinzneumann** [comment]
Sounds great, thanks a lot

Am 27.01.2024 17:32 schrieb baumwollschaf ***@***.***>:

I'll fix it this Weekend.

(mobil)

Heinzneumann ***@***.***> schrieb am Sa., 27. Jan. 2024,
09:46:

**Comment by baumwollschaf** [comment]
Should work now. Can't test properly because my free quota has been used up.

**Comment by baumwollschaf** [comment]
I mean for my free ApiKey.

**Comment by Heinzneumann** [comment]
Hallo 

 

Sorry see screen Shot

 



 

I deleted the Component in D12 end removed the .bpl in public\documents\...\bpl

Then i installen from th new (today date)

Und compiled the new example

Somewhat went wrong again.

 

Mit freundlichen Grüßen

 

Dr.Ing. Heinz Neumann

 

 

NH-Engineering

von Frays Str. 24

81245 München

 

Mail: ***@***.*** ***@***.***> 

Fax: 0049 89 881198

Tel.: 0049 89 886262

Mobile: 0170 290 6558

Web: www.nhengineering.de <http://www.nhengineering.de/> 

 

Datenschutzhinweis: Bitte beachten Sie, dass personenbezogene Daten zur Erfassung und Bearbeitung dieses Vorgangs aufgenommen werden können. Diese werden von ElektroniAnlagenPartner gemäß den Bestimmungen der DSGVO und des Bundesdatenschutzgesetzes 2018 (BDSG-neu) streng vertraulich behandelt. Gemäß Art. 13 DSGVO verweisen wir auf unsere ausführlichen Infortmationspflichten und Datenschutzerklärung, die Sie jederzeit per oben aufgeführter  E-Mail anfordern können.

---------------------------------------------------------------------------------------------------------------------------------------------

Vertraulichkeitshinweis Diese Nachricht ist ausschließlich für die adressierte Person oder Organisation (Empfänger) bestimmt und könnte vertrauliche und/oder persönliche Informationen enthalten. Empfängern, für die diese Nachricht nicht bestimmt ist, ist es nicht gestattet, diese zu lesen, zu kopieren, erneut zu übertragen oder anderweitig zu verwenden oder Maßnahmen zu ergreifen, die auf dem Inhalt dieser Nachricht basieren. Sollten Sie diese Nachricht irrtümlich erhalten haben, bitten wir Sie, sich mit dem Absender in Verbindung zu setzen und diese Nachricht unverzüglich von Ihrem Computer zu löschen. 

Vielen Dank für Ihre Mühe

 

Von: baumwollschaf ***@***.***> 
Gesendet: Sonntag, 28. Januar 2024 11:42
An: baumwollschaf/RDOpenAI ***@***.***>
Cc: Heinzneumann ***@***.***>; Author ***@***.***>
Betreff: Re: [baumwollschaf/RDOpenAI] RDopenai does not work in Delphi Vs 12 (Issue #5)

 

Should work now. Can't test properly because my free quota has been used up.

**Comment by Heinzneumann** [comment]
![image](https://github.com/baumwollschaf/RDOpenAI/assets/47383996/32c29d24-3773-46fe-9652-5ac759fd0eb2)
the screen shot

Error:
Error : Bad request
(as before)

**Comment by baumwollschaf** [comment]
I think your free contingent is up as well. Register a new OpenAI Account
with a unused cell phone no.

(mobil)

Heinzneumann ***@***.***> schrieb am So., 28. Jan. 2024,
12:04:

**Comment by baumwollschaf** [comment]
... To obtain a new free working ApiKey.

(mobil)

Ralph Dietrich ***@***.***> schrieb am So., 28. Jan. 2024,
12:14:

**Comment by baumwollschaf** [comment]
Try your call via PostMan and you'll get the same error.
Btw. You can debug the example to get more error info.

(mobil)

Ralph Dietrich ***@***.***> schrieb am So., 28. Jan. 2024,
12:15:

**Comment by baumwollschaf** [comment]
Sie können auch in deutsch schreiben...
Ihr freies Kontingent für Ihren ApiKey ist wahrscheinlich aufgebraucht.
(Hab das gleiche Problem.) Entweder zahlen Sie ab jetzt bei OpenAI oder Sie
erstellen einen neuen Account... Dann haben Sie wieder eine gewisse Anzahl
an freien Prompts bzw. REST calls pro ApiKey...
Viele Grüße.

(mobil)

Ralph Dietrich ***@***.***> schrieb am So., 28. Jan. 2024,
12:17:

**Comment by baumwollschaf** [comment]
Vielleicht liegt es auch an MAX_TOKENS, die vielleicht heruntergesetzt
werden müssen für ein bestimmtes Modell.

Maybe it's also due to MAX_TOKENS, which may need to be lowered for a
certain model.

(mobil)

Ralph Dietrich ***@***.***> schrieb am So., 28. Jan. 2024,
12:23:

**Comment by Heinzneumann** [comment]
Kontingent ist ok bei mir (bezahlt) und arbeitet auch unter d11

 

Ich hab schon versucht rein zudebuggen, aber hier kommt ein http exception in D12

 

if FAsynchronous then

  begin

    FRequest.ExecuteAsync(ChatCompletionCallback, True, True, DoCompletionHandlerWithError);

    Exit;

  end else begin

    FRequest.Execute;

 

 

Mit freundlichen Grüßen

 

Dr.Ing. Heinz Neumann

 

 

NH-Engineering

von Frays Str. 24

81245 München

 

Mail: ***@***.*** ***@***.***> 

Fax: 0049 89 881198

Tel.: 0049 89 886262

Mobile: 0170 290 6558

Web: www.nhengineering.de <http://www.nhengineering.de/> 

 

Datenschutzhinweis: Bitte beachten Sie, dass personenbezogene Daten zur Erfassung und Bearbeitung dieses Vorgangs aufgenommen werden können. Diese werden von ElektroniAnlagenPartner gemäß den Bestimmungen der DSGVO und des Bundesdatenschutzgesetzes 2018 (BDSG-neu) streng vertraulich behandelt. Gemäß Art. 13 DSGVO verweisen wir auf unsere ausführlichen Infortmationspflichten und Datenschutzerklärung, die Sie jederzeit per oben aufgeführter  E-Mail anfordern können.

---------------------------------------------------------------------------------------------------------------------------------------------

Vertraulichkeitshinweis Diese Nachricht ist ausschließlich für die adressierte Person oder Organisation (Empfänger) bestimmt und könnte vertrauliche und/oder persönliche Informationen enthalten. Empfängern, für die diese Nachricht nicht bestimmt ist, ist es nicht gestattet, diese zu lesen, zu kopieren, erneut zu übertragen oder anderweitig zu verwenden oder Maßnahmen zu ergreifen, die auf dem Inhalt dieser Nachricht basieren. Sollten Sie diese Nachricht irrtümlich erhalten haben, bitten wir Sie, sich mit dem Absender in Verbindung zu setzen und diese Nachricht unverzüglich von Ihrem Computer zu löschen. 

Vielen Dank für Ihre Mühe

 

Von: baumwollschaf ***@***.***> 
Gesendet: Sonntag, 28. Januar 2024 12:24
An: baumwollschaf/RDOpenAI ***@***.***>
Cc: Heinzneumann ***@***.***>; Author ***@***.***>
Betreff: Re: [baumwollschaf/RDOpenAI] RDopenai does not work in Delphi Vs 12 (Issue #5)

 

Sie können auch in deutsch schreiben... 
Ihr freies Kontingent für Ihren ApiKey ist wahrscheinlich aufgebraucht. 
(Hab das gleiche Problem.) Entweder zahlen Sie ab jetzt bei OpenAI oder Sie 
erstellen einen neuen Account... Dann haben Sie wieder eine gewisse Anzahl 
an freien Prompts bzw. REST calls pro ApiKey... 
Viele Grüße. 

(mobil) 

Ralph Dietrich ***@***.*** <mailto:***@***.***> > schrieb am So., 28. Jan. 2024, 
12:17:

**Comment by Heinzneumann** [comment]
Hier lande ich nach besagter Zeile:

Die Zeile voriger Mail ist in rd.openai.chatgpt.viewmodel! (sorry)

(in system)

{$IFDEF STACK_BASED_EXCEPTIONS}

procedure _TryFinallyExit;

asm

        XOR     EDX,EDX

        MOV     ECX,[ESP+4].TExcFrame.desc

        MOV     EAX,[ESP+4].TExcFrame.next

        ADD     ECX,TExcDesc.instructions

        MOV     FS:[EDX],EAX

{$IFDEF ALIGN_STACK}

        SUB      ESP, 12

{$ENDIF ALIGN_STACK}

        CALL    ECX

{$IFDEF ALIGN_STACK}

        ADD      ESP, 12

{$ENDIF ALIGN_STACK}

@@1:    RET     12

end;

{$ENDIF STACK_BASED_EXCEPTIONS}

 

Mit freundlichen Grüßen

 

Dr.Ing. Heinz Neumann

 

 

NH-Engineering

von Frays Str. 24

81245 München

 

Mail: ***@***.*** ***@***.***> 

Fax: 0049 89 881198

Tel.: 0049 89 886262

Mobile: 0170 290 6558

Web: www.nhengineering.de <http://www.nhengineering.de/> 

 

Datenschutzhinweis: Bitte beachten Sie, dass personenbezogene Daten zur Erfassung und Bearbeitung dieses Vorgangs aufgenommen werden können. Diese werden von ElektroniAnlagenPartner gemäß den Bestimmungen der DSGVO und des Bundesdatenschutzgesetzes 2018 (BDSG-neu) streng vertraulich behandelt. Gemäß Art. 13 DSGVO verweisen wir auf unsere ausführlichen Infortmationspflichten und Datenschutzerklärung, die Sie jederzeit per oben aufgeführter  E-Mail anfordern können.

---------------------------------------------------------------------------------------------------------------------------------------------

Vertraulichkeitshinweis Diese Nachricht ist ausschließlich für die adressierte Person oder Organisation (Empfänger) bestimmt und könnte vertrauliche und/oder persönliche Informationen enthalten. Empfängern, für die diese Nachricht nicht bestimmt ist, ist es nicht gestattet, diese zu lesen, zu kopieren, erneut zu übertragen oder anderweitig zu verwenden oder Maßnahmen zu ergreifen, die auf dem Inhalt dieser Nachricht basieren. Sollten Sie diese Nachricht irrtümlich erhalten haben, bitten wir Sie, sich mit dem Absender in Verbindung zu setzen und diese Nachricht unverzüglich von Ihrem Computer zu löschen. 

Vielen Dank für Ihre Mühe

 

Von: baumwollschaf ***@***.***> 
Gesendet: Sonntag, 28. Januar 2024 12:24
An: baumwollschaf/RDOpenAI ***@***.***>
Cc: Heinzneumann ***@***.***>; Author ***@***.***>
Betreff: Re: [baumwollschaf/RDOpenAI] RDopenai does not work in Delphi Vs 12 (Issue #5)

 

Sie können auch in deutsch schreiben... 
Ihr freies Kontingent für Ihren ApiKey ist wahrscheinlich aufgebraucht. 
(Hab das gleiche Problem.) Entweder zahlen Sie ab jetzt bei OpenAI oder Sie 
erstellen einen neuen Account... Dann haben Sie wieder eine gewisse Anzahl 
an freien Prompts bzw. REST calls pro ApiKey... 
Viele Grüße. 

(mobil) 

Ralph Dietrich ***@***.*** <mailto:***@***.***> > schrieb am So., 28. Jan. 2024, 
12:17:

**Comment by Heinzneumann** [comment]
Hier noch die Exception meldung:

 



 

 

Ich verwende immer gpt-4 und die selbe Frage.

In d11 geht das wunderbar!

 

Mit freundlichen Grüßen

 

Dr.Ing. Heinz Neumann

 

 

NH-Engineering

von Frays Str. 24

81245 München

 

Mail: ***@***.*** ***@***.***> 

Fax: 0049 89 881198

Tel.: 0049 89 886262

Mobile: 0170 290 6558

Web: www.nhengineering.de <http://www.nhengineering.de/> 

 

Datenschutzhinweis: Bitte beachten Sie, dass personenbezogene Daten zur Erfassung und Bearbeitung dieses Vorgangs aufgenommen werden können. Diese werden von ElektroniAnlagenPartner gemäß den Bestimmungen der DSGVO und des Bundesdatenschutzgesetzes 2018 (BDSG-neu) streng vertraulich behandelt. Gemäß Art. 13 DSGVO verweisen wir auf unsere ausführlichen Infortmationspflichten und Datenschutzerklärung, die Sie jederzeit per oben aufgeführter  E-Mail anfordern können.

---------------------------------------------------------------------------------------------------------------------------------------------

Vertraulichkeitshinweis Diese Nachricht ist ausschließlich für die adressierte Person oder Organisation (Empfänger) bestimmt und könnte vertrauliche und/oder persönliche Informationen enthalten. Empfängern, für die diese Nachricht nicht bestimmt ist, ist es nicht gestattet, diese zu lesen, zu kopieren, erneut zu übertragen oder anderweitig zu verwenden oder Maßnahmen zu ergreifen, die auf dem Inhalt dieser Nachricht basieren. Sollten Sie diese Nachricht irrtümlich erhalten haben, bitten wir Sie, sich mit dem Absender in Verbindung zu setzen und diese Nachricht unverzüglich von Ihrem Computer zu löschen. 

Vielen Dank für Ihre Mühe

 

Von: baumwollschaf ***@***.***> 
Gesendet: Sonntag, 28. Januar 2024 12:51
An: baumwollschaf/RDOpenAI ***@***.***>
Cc: Heinzneumann ***@***.***>; Author ***@***.***>
Betreff: Re: [baumwollschaf/RDOpenAI] RDopenai does not work in Delphi Vs 12 (Issue #5)

 

Vielleicht liegt es auch an MAX_TOKENS, die vielleicht heruntergesetzt 
werden müssen für ein bestimmtes Modell. 

Maybe it's also due to MAX_TOKENS, which may need to be lowered for a 
certain model. 

(mobil) 

Ralph Dietrich ***@***.*** <mailto:***@***.***> > schrieb am So., 28. Jan. 2024, 
12:23:

**Comment by Heinzneumann** [comment]
Könnte es etwas mit der in D12 geänderten Json zu tun haben, dass der http request anders ist?

 

Mit freundlichen Grüßen

 

Dr.Ing. Heinz Neumann

 

 

NH-Engineering

von Frays Str. 24

81245 München

 

Mail: ***@***.*** ***@***.***> 

Fax: 0049 89 881198

Tel.: 0049 89 886262

Mobile: 0170 290 6558

Web: www.nhengineering.de <http://www.nhengineering.de/> 

 

Datenschutzhinweis: Bitte beachten Sie, dass personenbezogene Daten zur Erfassung und Bearbeitung dieses Vorgangs aufgenommen werden können. Diese werden von ElektroniAnlagenPartner gemäß den Bestimmungen der DSGVO und des Bundesdatenschutzgesetzes 2018 (BDSG-neu) streng vertraulich behandelt. Gemäß Art. 13 DSGVO verweisen wir auf unsere ausführlichen Infortmationspflichten und Datenschutzerklärung, die Sie jederzeit per oben aufgeführter  E-Mail anfordern können.

---------------------------------------------------------------------------------------------------------------------------------------------

Vertraulichkeitshinweis Diese Nachricht ist ausschließlich für die adressierte Person oder Organisation (Empfänger) bestimmt und könnte vertrauliche und/oder persönliche Informationen enthalten. Empfängern, für die diese Nachricht nicht bestimmt ist, ist es nicht gestattet, diese zu lesen, zu kopieren, erneut zu übertragen oder anderweitig zu verwenden oder Maßnahmen zu ergreifen, die auf dem Inhalt dieser Nachricht basieren. Sollten Sie diese Nachricht irrtümlich erhalten haben, bitten wir Sie, sich mit dem Absender in Verbindung zu setzen und diese Nachricht unverzüglich von Ihrem Computer zu löschen. 

Vielen Dank für Ihre Mühe

 

Von: baumwollschaf ***@***.***> 
Gesendet: Sonntag, 28. Januar 2024 12:51
An: baumwollschaf/RDOpenAI ***@***.***>
Cc: Heinzneumann ***@***.***>; Author ***@***.***>
Betreff: Re: [baumwollschaf/RDOpenAI] RDopenai does not work in Delphi Vs 12 (Issue #5)

 

Vielleicht liegt es auch an MAX_TOKENS, die vielleicht heruntergesetzt 
werden müssen für ein bestimmtes Modell. 

Maybe it's also due to MAX_TOKENS, which may need to be lowered for a 
certain model. 

(mobil) 

Ralph Dietrich ***@***.*** <mailto:***@***.***> > schrieb am So., 28. Jan. 2024, 
12:23:

**Comment by baumwollschaf** [comment]
Komisch, bei mir nicht. Ich mache das morgen nochmal in Ruhe...


(mobil)

Heinzneumann ***@***.***> schrieb am So., 28. Jan. 2024,
12:54:

**Comment by baumwollschaf** [comment]
Ich mache auch mal morgen ein Diff auf die REST Library... Vielleicht hat
sich da was geändert...

(mobil)

Ralph Dietrich ***@***.***> schrieb am So., 28. Jan. 2024,
14:05:

**Comment by Heinzneumann** [comment]
Danke, finde dein Engagement toll!

Kein Stress, hab ja noch D11!

 

Mit freundlichen Grüßen

 

Dr.Ing. Heinz Neumann

 

 

NH-Engineering

von Frays Str. 24

81245 München

 

Mail: ***@***.*** ***@***.***> 

Fax: 0049 89 881198

Tel.: 0049 89 886262

Mobile: 0170 290 6558

Web: www.nhengineering.de <http://www.nhengineering.de/> 

 

Datenschutzhinweis: Bitte beachten Sie, dass personenbezogene Daten zur Erfassung und Bearbeitung dieses Vorgangs aufgenommen werden können. Diese werden von ElektroniAnlagenPartner gemäß den Bestimmungen der DSGVO und des Bundesdatenschutzgesetzes 2018 (BDSG-neu) streng vertraulich behandelt. Gemäß Art. 13 DSGVO verweisen wir auf unsere ausführlichen Infortmationspflichten und Datenschutzerklärung, die Sie jederzeit per oben aufgeführter  E-Mail anfordern können.

---------------------------------------------------------------------------------------------------------------------------------------------

Vertraulichkeitshinweis Diese Nachricht ist ausschließlich für die adressierte Person oder Organisation (Empfänger) bestimmt und könnte vertrauliche und/oder persönliche Informationen enthalten. Empfängern, für die diese Nachricht nicht bestimmt ist, ist es nicht gestattet, diese zu lesen, zu kopieren, erneut zu übertragen oder anderweitig zu verwenden oder Maßnahmen zu ergreifen, die auf dem Inhalt dieser Nachricht basieren. Sollten Sie diese Nachricht irrtümlich erhalten haben, bitten wir Sie, sich mit dem Absender in Verbindung zu setzen und diese Nachricht unverzüglich von Ihrem Computer zu löschen. 

Vielen Dank für Ihre Mühe

 

Von: baumwollschaf ***@***.***> 
Gesendet: Sonntag, 28. Januar 2024 14:07
An: baumwollschaf/RDOpenAI ***@***.***>
Cc: Heinzneumann ***@***.***>; Author ***@***.***>
Betreff: Re: [baumwollschaf/RDOpenAI] RDopenai does not work in Delphi Vs 12 (Issue #5)

 

Ich mache auch mal morgen ein Diff auf die REST Library... Vielleicht hat 
sich da was geändert... 

(mobil) 

Ralph Dietrich ***@***.*** <mailto:***@***.***> > schrieb am So., 28. Jan. 2024, 
14:05:

**Comment by baumwollschaf** [comment]
Danke für das Feedback...

(mobil)

Heinzneumann ***@***.***> schrieb am So., 28. Jan. 2024,
14:43:

**Comment by baumwollschaf** [comment]
Guten Morgen, bitte nochmal testen. Sollte jetzt funktionieren. Hab ein Switch bezüglich Delphi11 und Delphi 12 eingebaut..., d.h. Delphi 11 ist die Ausnahme. Es sollte mit zukünftigen Versionen funktionieren...

**Comment by baumwollschaf** [comment]
Also... Embarcadero hat in den REST-Classes tatsächlich insofern Änderungen gemacht, dass die JsonOptions, mit in den String includiert werden (In Delphi 11 nicht, sofern default). Ich finde, dass das schon sehr dramatische Änderungen sind und dass Embarcadero da viel sensibler hätte rangehen können...

**Comment by Heinzneumann** [comment]
Hallo 

 

Vielen herzlichen Dank für die schnelle Hilfe.

Bezüglich der Umstellung hätte man das sicher auch eleganter und kompatibler lösen können, da haben Sie völlig recht!

 

Aber dennoch eine super Lösung die Sie geschaffen haben!

 

Mit freundlichen Grüßen

 

Dr.Ing. Heinz Neumann

 

 

NH-Engineering

von Frays Str. 24

81245 München

 

Mail: ***@***.*** ***@***.***> 

Fax: 0049 89 881198

Tel.: 0049 89 886262

Mobile: 0170 290 6558

Web: www.nhengineering.de <http://www.nhengineering.de/> 

 

Datenschutzhinweis: Bitte beachten Sie, dass personenbezogene Daten zur Erfassung und Bearbeitung dieses Vorgangs aufgenommen werden können. Diese werden von ElektroniAnlagenPartner gemäß den Bestimmungen der DSGVO und des Bundesdatenschutzgesetzes 2018 (BDSG-neu) streng vertraulich behandelt. Gemäß Art. 13 DSGVO verweisen wir auf unsere ausführlichen Infortmationspflichten und Datenschutzerklärung, die Sie jederzeit per oben aufgeführter  E-Mail anfordern können.

---------------------------------------------------------------------------------------------------------------------------------------------

Vertraulichkeitshinweis Diese Nachricht ist ausschließlich für die adressierte Person oder Organisation (Empfänger) bestimmt und könnte vertrauliche und/oder persönliche Informationen enthalten. Empfängern, für die diese Nachricht nicht bestimmt ist, ist es nicht gestattet, diese zu lesen, zu kopieren, erneut zu übertragen oder anderweitig zu verwenden oder Maßnahmen zu ergreifen, die auf dem Inhalt dieser Nachricht basieren. Sollten Sie diese Nachricht irrtümlich erhalten haben, bitten wir Sie, sich mit dem Absender in Verbindung zu setzen und diese Nachricht unverzüglich von Ihrem Computer zu löschen. 

Vielen Dank für Ihre Mühe

 

Von: baumwollschaf ***@***.***> 
Gesendet: Montag, 29. Januar 2024 10:31
An: baumwollschaf/RDOpenAI ***@***.***>
Cc: Heinzneumann ***@***.***>; Author ***@***.***>
Betreff: Re: [baumwollschaf/RDOpenAI] RDopenai does not work in Delphi Vs 12 (Issue #5)

 

Also... Embarcadero hat in den REST-Classes tatsächlich insofern Änderungen gemacht, dass die JsonOptions, mit in den String includiert werden (In Delphi 11 nicht, sofern default). Ich finde, dass das schon sehr dramatische Änderungen sind und dass Embarcadero da viel sensibler hätte rangehen können...

**Comment by baumwollschaf** [comment]
Gerne :-)

(mobil)

Heinzneumann ***@***.***> schrieb am Mo., 29. Jan. 2024,
14:37:
