### ISSUE TITLE
Error: Too Many Requests

### ISSUE THREAD

**Issue by PeterPanino** [baumwollschaf/RDOpenAI#6]
I always get the error message:

**Error: Too Many Requests**

Although I have used a valid API key.

Delphi 12

**Comment by baumwollschaf** [comment]
your free number of queries seems to be exceeded.

PeterPanino ***@***.***> schrieb am Sa., 10. Feb. 2024, 12:38:

**Comment by PeterPanino** [comment]
> your free number of queries seems to be exceeded.

However, I have provided a valid API key.

**Comment by baumwollschaf** [comment]
Yes, it could be valid. But free is only a number of calls.

**Comment by baumwollschaf** [comment]
Did you pay for your ApiKey?

**Comment by PeterPanino** [comment]
I am a paying OpenAI customer.

**Comment by baumwollschaf** [comment]
Try to check right here:
https://help.openai.com/en/articles/5955604-how-can-i-solve-429-too-many-requests-errors

**Comment by baumwollschaf** [comment]
Try different Models, temperatures and/or max tokens...

**Comment by baumwollschaf** [comment]
Here another Link: https://platform.openai.com/docs/guides/rate-limits/usage-tiers?context=tier-free
